---
development:
  cloud_name: plantconnect
  api_key: '954749159772625'
  api_secret: jklvQrjWQIBFdDUd78I_IvNXnEs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: plantconnect
  api_key: '954749159772625'
  api_secret: jklvQrjWQIBFdDUd78I_IvNXnEs
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: plantconnect
  api_key: '954749159772625'
  api_secret: jklvQrjWQIBFdDUd78I_IvNXnEs
  enhance_image_tag: true
  static_file_support: false
